// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrzK9KXx5FL6rbuOtQhgZMYMsmrNO2TXs',
    appId: '1:859950300277:web:d39fb932b96ef618fe0c3c',
    messagingSenderId: '859950300277',
    projectId: 'gamifiedtravellapp',
    authDomain: 'gamifiedtravellapp.firebaseapp.com',
    storageBucket: 'gamifiedtravellapp.firebasestorage.app',
    measurementId: 'G-Q92XMQ6CGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeGa3ndwxaikkqnf2t1NgwnPrYsGRsAao',
    appId: '1:859950300277:android:4d62a05c3fe831d6fe0c3c',
    messagingSenderId: '859950300277',
    projectId: 'gamifiedtravellapp',
    storageBucket: 'gamifiedtravellapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQdKQha4tiYijUjlDQi6zpnX_l_wrm5gw',
    appId: '1:859950300277:ios:807d209598a8f8ebfe0c3c',
    messagingSenderId: '859950300277',
    projectId: 'gamifiedtravellapp',
    storageBucket: 'gamifiedtravellapp.firebasestorage.app',
    iosBundleId: 'com.example.cityquest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQdKQha4tiYijUjlDQi6zpnX_l_wrm5gw',
    appId: '1:859950300277:ios:807d209598a8f8ebfe0c3c',
    messagingSenderId: '859950300277',
    projectId: 'gamifiedtravellapp',
    storageBucket: 'gamifiedtravellapp.firebasestorage.app',
    iosBundleId: 'com.example.cityquest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrzK9KXx5FL6rbuOtQhgZMYMsmrNO2TXs',
    appId: '1:859950300277:web:4cb2f9aa9e3efec6fe0c3c',
    messagingSenderId: '859950300277',
    projectId: 'gamifiedtravellapp',
    authDomain: 'gamifiedtravellapp.firebaseapp.com',
    storageBucket: 'gamifiedtravellapp.firebasestorage.app',
    measurementId: 'G-BS7494ZL77',
  );
}
